# Generated by Django 5.2.8 on 2025-11-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Reference_Number', models.IntegerField()),
                ('Gender', models.CharField(max_length=1)),
                ('Department', models.CharField(max_length=10)),
                ('Date_of_Birth', models.DateField()),
                ('Phone_Number', models.IntegerField()),
                ('marksPercentage', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
